/*
 * PanelMotorBusqueda.java
 *
 * Created on 29 de julio de 2008, 00:42
 */
package panels.busqueda;

import configuration.AdvancedProperty;
import configuration.defaultontology.types.DefaultProperty;
import controladores.ControladorPanelMotorBusqueda;
import javax.swing.JPanel;
import panels.*;
import gui.FramePrincipal;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import modelo.BusinessDelegate;
import panels.busqueda.proprincipal.PropiedadPrincipal;
import panels.busqueda.proprincipal.PropiedadPrincipalDate;
import panels.busqueda.proprincipal.PropiedadPrincipalInteger;
import panels.busqueda.proprincipal.PropiedadPrincipalString;
import panels.busqueda.resultado.PanelResultado;
import panels.busqueda.resultado.PanelResultadoVuelo;
import panels.busqueda.tipodatoproavanzada.PanelAnyType;
import panels.busqueda.tipodatoproavanzada.PanelBoolean;
import panels.busqueda.tipodatoproavanzada.PanelDate;
import panels.busqueda.tipodatoproavanzada.PanelTipoDato;
import varios.Constantes;
import vistas.VistaMotorBusqueda;
import vo.busqueda.ConsultaVO;
import vo.busqueda.IndividualVO;

/**
 *
 * @author  Administrador
 */
public class PanelMotorBusqueda extends javax.swing.JPanel {

    private FramePrincipal main;
    private VistaMotorBusqueda vistaMotorBusqueda;
    private boolean buscarVuelos;
    private boolean buscarAlojameinto;
    private boolean buscarAuto;
    private List<PanelTipoDato> proAdvVuelo;
    private List<PanelTipoDato> proAdvAlojamiento;
    private List<PanelTipoDato> proAdvAuto;
    private List<PropiedadPrincipal> proVuelo;
    private List<PropiedadPrincipal> proAlojamiento;
    private List<PropiedadPrincipal> proAuto;

    /** Creates new form PanelMotorBusqueda */
    public PanelMotorBusqueda(FramePrincipal main, VistaMotorBusqueda vista) {
        this.main = main;
        this.vistaMotorBusqueda = vista;
        initComponents();
        proAdvAlojamiento = new ArrayList<PanelTipoDato>();
        proAdvVuelo = new ArrayList<PanelTipoDato>();
        proAdvAuto = new ArrayList<PanelTipoDato>();
        proAlojamiento = new ArrayList<PropiedadPrincipal>();
        proVuelo = new ArrayList<PropiedadPrincipal>();
        proAuto = new ArrayList<PropiedadPrincipal>();
        generarOpcionesPrincipales();
        generarOpcionesAvanzadas();
        this.panelOpcionesAvanzadaAlojamiento.setVisible(false);
        this.panelOpcionesAvanzadasAutos.setVisible(false);
        this.panelOpcionesAvanzadasVuelos.setVisible(false);
    }

    private void cargoPropiedadPrincipal(DefaultProperty prop, JPanel panelAlojamiento, List<PropiedadPrincipal> proAlojamiento) {
        PropiedadPrincipal panel = null;
        switch (prop.getTipoDato()) {
            case DATE:
                panel = new PropiedadPrincipalDate(prop.getName());
                break;
            case INTEGER:
                panel = new PropiedadPrincipalInteger(prop.getName());
                break;
            case STRING:
                panel = new PropiedadPrincipalString(prop.getName());
                break;
        }
        
        proAlojamiento.add(panel);
        panelAlojamiento.add((JPanel) panel);
    }

    private void cargoPropiedadAvanzada(AdvancedProperty pro, JPanel panelOpcionesAvanzadasVuelosDefault, List<PanelTipoDato> paneles) {
        PanelTipoDato panel = null;
        switch (pro.getTipoDato()) {
            case ANY:
                panel = new PanelAnyType(pro.getNombre(), pro.getTipoDato());
                break;
            case BOOLEAN:
                panel = new PanelBoolean(pro.getNombre());
                break;
            case DATE:
                panel = new PanelDate(pro.getNombre());
                break;
            case DOUBLE:
                panel = new PanelAnyType(pro.getNombre(), pro.getTipoDato());
                break;
            case FLOAT:
                panel = new PanelAnyType(pro.getNombre(), pro.getTipoDato());
                break;
            case INTEGER:
                panel = new PanelAnyType(pro.getNombre(), pro.getTipoDato());
                break;
            case STRING:
                panel = new PanelAnyType(pro.getNombre(), pro.getTipoDato());
                break;
        }
        paneles.add(panel);
        panelOpcionesAvanzadasVuelosDefault.add((JPanel) panel);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelMotorBusquedaVuelo = new javax.swing.JPanel();
        panelOpcionesAvanzadasVuelos = new javax.swing.JPanel();
        panelVuelo = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        panelResultadoVuelo = new javax.swing.JPanel();
        toggleButtonOpcionesAvanzadasVuelo = new javax.swing.JToggleButton();
        buttonBuscarVuelos = new javax.swing.JButton();
        panelMotorBusquedaHotel = new javax.swing.JPanel();
        panelAlojamiento = new javax.swing.JPanel();
        panelOpcionesAvanzadaAlojamiento = new javax.swing.JPanel();
        panelResultadoAlojamiento = new javax.swing.JPanel();
        toggleButtonOpAvAlojamiento = new javax.swing.JToggleButton();
        buttonBuscarAlojamiento = new javax.swing.JButton();
        panelMotorBusquedaAuto = new javax.swing.JPanel();
        panelAutos = new javax.swing.JPanel();
        panelOpcionesAvanzadasAutos = new javax.swing.JPanel();
        panelResultadoAutos = new javax.swing.JPanel();
        toggleButtonOpAvAuto = new javax.swing.JToggleButton();
        buttonBuscarAuto = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panelOpcionesAvanzadasVuelos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelOpcionesAvanzadasVuelos.setPreferredSize(new java.awt.Dimension(414, 182));
        panelOpcionesAvanzadasVuelos.setLayout(new java.awt.GridLayout(0, 1));

        panelVuelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelVuelo.setPreferredSize(new java.awt.Dimension(414, 216));
        panelVuelo.setLayout(new java.awt.GridLayout(6, 1));

        panelResultadoVuelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelResultadoVuelo.setPreferredSize(new java.awt.Dimension(513, 453));
        panelResultadoVuelo.setRequestFocusEnabled(false);
        panelResultadoVuelo.setLayout(new java.awt.GridLayout(0, 1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelResultadoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(panelResultadoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        toggleButtonOpcionesAvanzadasVuelo.setText("Opciones avanzadas");
        toggleButtonOpcionesAvanzadasVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonOpcionesAvanzadasVueloActionPerformed(evt);
            }
        });

        buttonBuscarVuelos.setText("Buscar vuelos");
        buttonBuscarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarVuelosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMotorBusquedaVueloLayout = new javax.swing.GroupLayout(panelMotorBusquedaVuelo);
        panelMotorBusquedaVuelo.setLayout(panelMotorBusquedaVueloLayout);
        panelMotorBusquedaVueloLayout.setHorizontalGroup(
            panelMotorBusquedaVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMotorBusquedaVueloLayout.createSequentialGroup()
                .addGroup(panelMotorBusquedaVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMotorBusquedaVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelMotorBusquedaVueloLayout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(toggleButtonOpcionesAvanzadasVuelo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonBuscarVuelos)
                            .addGap(21, 21, 21))
                        .addGroup(panelMotorBusquedaVueloLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(panelVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(panelMotorBusquedaVueloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelOpcionesAvanzadasVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMotorBusquedaVueloLayout.setVerticalGroup(
            panelMotorBusquedaVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMotorBusquedaVueloLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelMotorBusquedaVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMotorBusquedaVueloLayout.createSequentialGroup()
                        .addComponent(panelVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMotorBusquedaVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toggleButtonOpcionesAvanzadasVuelo)
                            .addComponent(buttonBuscarVuelos))
                        .addGap(18, 18, 18)
                        .addComponent(panelOpcionesAvanzadasVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vuelos", panelMotorBusquedaVuelo);

        panelAlojamiento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAlojamiento.setPreferredSize(new java.awt.Dimension(414, 216));
        panelAlojamiento.setLayout(new java.awt.GridLayout(0, 1));

        panelOpcionesAvanzadaAlojamiento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelOpcionesAvanzadaAlojamiento.setPreferredSize(new java.awt.Dimension(414, 182));
        panelOpcionesAvanzadaAlojamiento.setLayout(new java.awt.GridLayout(0, 1));

        panelResultadoAlojamiento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelResultadoAlojamiento.setPreferredSize(new java.awt.Dimension(513, 453));
        panelResultadoAlojamiento.setLayout(new java.awt.GridLayout(0, 1));

        toggleButtonOpAvAlojamiento.setText("Opciones avanzadas");
        toggleButtonOpAvAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonOpAvAlojamientoActionPerformed(evt);
            }
        });

        buttonBuscarAlojamiento.setText("Buscar alojamietno");
        buttonBuscarAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarAlojamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMotorBusquedaHotelLayout = new javax.swing.GroupLayout(panelMotorBusquedaHotel);
        panelMotorBusquedaHotel.setLayout(panelMotorBusquedaHotelLayout);
        panelMotorBusquedaHotelLayout.setHorizontalGroup(
            panelMotorBusquedaHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMotorBusquedaHotelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMotorBusquedaHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMotorBusquedaHotelLayout.createSequentialGroup()
                        .addGroup(panelMotorBusquedaHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelOpcionesAvanzadaAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelMotorBusquedaHotelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(toggleButtonOpAvAlojamiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBuscarAlojamiento)
                        .addGap(20, 20, 20)))
                .addComponent(panelResultadoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMotorBusquedaHotelLayout.setVerticalGroup(
            panelMotorBusquedaHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMotorBusquedaHotelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMotorBusquedaHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelResultadoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMotorBusquedaHotelLayout.createSequentialGroup()
                        .addComponent(panelAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMotorBusquedaHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toggleButtonOpAvAlojamiento)
                            .addComponent(buttonBuscarAlojamiento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelOpcionesAvanzadaAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Hoteles", panelMotorBusquedaHotel);

        panelAutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAutos.setPreferredSize(new java.awt.Dimension(414, 216));
        panelAutos.setLayout(new java.awt.GridLayout(0, 1));

        panelOpcionesAvanzadasAutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelOpcionesAvanzadasAutos.setPreferredSize(new java.awt.Dimension(414, 182));
        panelOpcionesAvanzadasAutos.setLayout(new java.awt.GridLayout(0, 1));

        panelResultadoAutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelResultadoAutos.setPreferredSize(new java.awt.Dimension(513, 453));
        panelResultadoAutos.setLayout(new java.awt.GridLayout(1, 1));

        toggleButtonOpAvAuto.setText("Opciones avanzadas");
        toggleButtonOpAvAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonOpAvAutoActionPerformed(evt);
            }
        });

        buttonBuscarAuto.setText("Buscar auto");
        buttonBuscarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarAutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMotorBusquedaAutoLayout = new javax.swing.GroupLayout(panelMotorBusquedaAuto);
        panelMotorBusquedaAuto.setLayout(panelMotorBusquedaAutoLayout);
        panelMotorBusquedaAutoLayout.setHorizontalGroup(
            panelMotorBusquedaAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMotorBusquedaAutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMotorBusquedaAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMotorBusquedaAutoLayout.createSequentialGroup()
                        .addGroup(panelMotorBusquedaAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelOpcionesAvanzadasAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelMotorBusquedaAutoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(toggleButtonOpAvAuto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBuscarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addComponent(panelResultadoAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMotorBusquedaAutoLayout.setVerticalGroup(
            panelMotorBusquedaAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMotorBusquedaAutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMotorBusquedaAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelResultadoAutos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMotorBusquedaAutoLayout.createSequentialGroup()
                        .addComponent(panelAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMotorBusquedaAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toggleButtonOpAvAuto)
                            .addComponent(buttonBuscarAuto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelOpcionesAvanzadasAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Autos", panelMotorBusquedaAuto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void toggleButtonOpcionesAvanzadasVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonOpcionesAvanzadasVueloActionPerformed
        if (((JToggleButton) evt.getSource()).isSelected()) {
            panelOpcionesAvanzadasVuelos.setVisible(true);
            this.repaint();
        } else {
            panelOpcionesAvanzadasVuelos.setVisible(false);
            for (PanelTipoDato panel : proAdvVuelo) {
                panel.clearData();
            }
            this.repaint();
        }
}//GEN-LAST:event_toggleButtonOpcionesAvanzadasVueloActionPerformed

private void buttonBuscarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarVuelosActionPerformed
    ((ControladorPanelMotorBusqueda) vistaMotorBusqueda.getControlador()).doBuscarVuelos(true);
}//GEN-LAST:event_buttonBuscarVuelosActionPerformed

private void toggleButtonOpAvAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonOpAvAlojamientoActionPerformed
    if (((JToggleButton) evt.getSource()).isSelected()) {
        panelOpcionesAvanzadaAlojamiento.setVisible(true);
        this.repaint();
    } else {
        panelOpcionesAvanzadaAlojamiento.setVisible(false);
        for (PanelTipoDato panel : proAdvAlojamiento) {
            panel.clearData();
        }
        this.repaint();
    }
}//GEN-LAST:event_toggleButtonOpAvAlojamientoActionPerformed

private void toggleButtonOpAvAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonOpAvAutoActionPerformed
    if (((JToggleButton) evt.getSource()).isSelected()) {
        panelOpcionesAvanzadasAutos.setVisible(true);
        this.repaint();
    } else {
        panelOpcionesAvanzadasAutos.setVisible(false);
        for (PanelTipoDato panel : proAdvAuto) {
            panel.clearData();
        }
        this.repaint();
    }
}//GEN-LAST:event_toggleButtonOpAvAutoActionPerformed

private void buttonBuscarAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarAlojamientoActionPerformed
    ((ControladorPanelMotorBusqueda) vistaMotorBusqueda.getControlador()).doBuscarAlojamiento(true);
}//GEN-LAST:event_buttonBuscarAlojamientoActionPerformed

private void buttonBuscarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarAutoActionPerformed
    ((ControladorPanelMotorBusqueda) vistaMotorBusqueda.getControlador()).doBuscarAuto(true);
}//GEN-LAST:event_buttonBuscarAutoActionPerformed

    public void update() {
        if (isBuscarVuelos()) {
            buscarVuelos();
        }
        if (isBuscarAuto()) {
            buscarAuto();
        }
        if (isBuscarAlojameinto()) {
            buscarAlojamiento();
        }
    }

    private void buscarAlojamiento() {
        panelResultadoAlojamiento.removeAll();
        this.repaint();
        if (validarInputAlojamiento()) {
            ConsultaVO hotelVO = obtenerDatosConsultaAlojamiento();
            //TODO Hasta aca esta bien, falta la busqueda y mostrar el resultado
            List<IndividualVO> indVuelos = ((BusinessDelegate) vistaMotorBusqueda.getModelo()).buscarHotel(hotelVO, this.main.getConfiguration().getDefaultOntology());
            if (!indVuelos.isEmpty()) {
                //Mostrar los resultados
                PanelResultado resultado;
                for (IndividualVO individualVO : indVuelos) {
                    resultado = new PanelResultado(individualVO);
                    resultado.setVisible(true);
                    panelResultadoAlojamiento.add(resultado);
                }
                this.repaint();
            } else {
                //Mandar cartel diciendo que no se encontro nada
                JOptionPane.showMessageDialog(this, "La consulta no arrojo ningun resultado", Constantes.APPLICATION_NAME, JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Completar todos los campos obligatorios", Constantes.APPLICATION_NAME, JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarAuto() {
        panelResultadoAutos.removeAll();
        this.repaint();
        if (validarInputAuto()) {
            ConsultaVO autoVO = obtenerDatosConsultaAuto();
            //TODO Hasta aca esta bien, falta la busqueda y mostrar el resultado
            List<IndividualVO> indVuelos = ((BusinessDelegate) vistaMotorBusqueda.getModelo()).buscarAutos(autoVO, this.main.getConfiguration().getDefaultOntology());
            if (!indVuelos.isEmpty()) {
                //Mostrar los resultados
                PanelResultado resultado;
                for (IndividualVO individualVO : indVuelos) {
                    resultado = new PanelResultado(individualVO);
                    resultado.setVisible(true);
                    panelResultadoAutos.add(resultado);
                }
                this.repaint();
            } else {
                //Mandar cartel diciendo que no se encontro nada
                JOptionPane.showMessageDialog(this, "La consulta no arrojo ningun resultado", Constantes.APPLICATION_NAME, JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Completar todos los campos obligatorios", Constantes.APPLICATION_NAME, JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarVuelos() {
        panelResultadoVuelo.removeAll();
        this.repaint();
        if (validarInputVuelo()) {
            ConsultaVO vueloVO = obtenerDatosConsultaVuelo();
            //TODO Hasta aca esta bien, falta la busqueda y mostrar el resultado
            List<IndividualVO> indVuelos = ((BusinessDelegate) vistaMotorBusqueda.getModelo()).buscarVuelos(vueloVO, this.main.getConfiguration().getDefaultOntology());
            if(!indVuelos.isEmpty()){
                //Mostrar los resultados
                PanelResultado resultado;
                for (IndividualVO individualVO : indVuelos) {
                    resultado = new PanelResultado(individualVO);
                    resultado.setVisible(true);
                    panelResultadoVuelo.add(resultado);
                }
                this.repaint();
            }else{
                //Mandar cartel diciendo que no se encontro nada
                JOptionPane.showMessageDialog(this, "La consulta no arrojo ningun resultado", Constantes.APPLICATION_NAME, JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Completar todos los campos obligatorios", Constantes.APPLICATION_NAME, JOptionPane.ERROR_MESSAGE);
        }
    }


    public void cargarPanelBusquedaVuelo(PanelResultadoVuelo panel, IndividualVO ind) {
    }

    private boolean validarInputAuto() {
        //Primero valido datos principales
        for(PropiedadPrincipal panel : proAuto){
            if(!panel.checkInput()){
                return false;
            }
        }
        //Ahora las avanzadas
        for (PanelTipoDato panel : proAdvAuto) {
            if (panel.isActived()) {
                if (!panel.checkInput()) {
                    return false;
                }
            }
        }
        return true;
    }

    private boolean validarInputAlojamiento() {
        //Primero valido datos principales
        for(PropiedadPrincipal panel : proAlojamiento){
            if(!panel.checkInput()){
                return false;
            }
        }
        //Ahora las avanzadas
        for (PanelTipoDato panel : proAdvAlojamiento) {
            if (panel.isActived()) {
                if (!panel.checkInput()) {
                    return false;
                }
            }
        }
        return true;
    }

    private boolean validarInputVuelo() {
        //Primero valido datos principales
        for(PropiedadPrincipal panel : proVuelo){
            if(!panel.checkInput()){
                return false;
            }
        }
        //Ahora las avanzadas
//        for (PanelTipoDato panel : proAdvVuelo) {
//            if (panel.isActived()) {
//                if (!panel.checkInput()) {
//                    return false;
//                }
//            }
//        }
        return true;
    }

    private ConsultaVO obtenerDatosConsultaAuto() {
        ConsultaVO auto = new ConsultaVO();
        for(PropiedadPrincipal pro : proAuto){
            auto.getPropiedadesPrincipales().put(pro.getNombrePropiedad(), pro.getValor());
        }
        for (PanelTipoDato panel : proAdvAuto) {
            if (panel.isActived()) {
                auto.getPropiedadesAvanzadas().put(panel.getNombre(), panel.getValue());
            }
        }
        return auto;
    }

    private ConsultaVO obtenerDatosConsultaAlojamiento() {
        ConsultaVO hotel = new ConsultaVO();
        for(PropiedadPrincipal pro : proAlojamiento){
            hotel.getPropiedadesPrincipales().put(pro.getNombrePropiedad(), pro.getValor());
        }
        for (PanelTipoDato panel : proAdvAlojamiento) {
            if (panel.isActived()) {
                hotel.getPropiedadesAvanzadas().put(panel.getNombre(), panel.getValue());
            }
        }
        return hotel;
    }

    private ConsultaVO obtenerDatosConsultaVuelo() {
        ConsultaVO vuelo = new ConsultaVO();
        for(PropiedadPrincipal pro : proVuelo){
            vuelo.getPropiedadesPrincipales().put(pro.getNombrePropiedad(), pro.getValor());
        }
        for (PanelTipoDato panel : proAdvVuelo) {
            if(panel.isActived())
                vuelo.getPropiedadesAvanzadas().put(panel.getNombre(), panel.getValue());
        }
        return vuelo;
    }

    private void generarOpcionesPrincipales() {
        List<DefaultProperty> props = this.main.getConfiguration().getDefaultOntology().getAlojamiento().getDefaultProperties();
        for(DefaultProperty prop : props){
            cargoPropiedadPrincipal(prop,panelAlojamiento,proAlojamiento);
        }
        props = this.main.getConfiguration().getDefaultOntology().getTranslado().getDefaultProperties();
        for(DefaultProperty prop : props){
            cargoPropiedadPrincipal(prop,panelAutos,proAuto);
        }
        props = this.main.getConfiguration().getDefaultOntology().getViaje().getDefaultProperties();
        for(DefaultProperty prop : props){
            cargoPropiedadPrincipal(prop,panelVuelo,proVuelo);
        }
    }

    private void generarOpcionesAvanzadas() {
        Vector<AdvancedProperty> advPro = this.main.getConfiguration().getPropiedadesAvanzadasVuelo();
        for (AdvancedProperty pro : advPro) {
            cargoPropiedadAvanzada(pro, panelOpcionesAvanzadasVuelos, proAdvVuelo);
        }
        advPro = this.main.getConfiguration().getPropiedadesAvanzadasHotel();
        for (AdvancedProperty pro : advPro) {
            cargoPropiedadAvanzada(pro, panelOpcionesAvanzadaAlojamiento, proAdvAlojamiento);
        }
        advPro = this.main.getConfiguration().getPropiedadesAvanzadasAuto();
        for (AdvancedProperty pro : advPro) {
            cargoPropiedadAvanzada(pro, panelOpcionesAvanzadasAutos, proAdvAuto);
        }
    }

    public void setVistaMotorBusqueda(VistaMotorBusqueda vista) {
        this.vistaMotorBusqueda = vista;
    }

    public VistaMotorBusqueda getVistaMotorBusqueda() {
        return this.vistaMotorBusqueda;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscarAlojamiento;
    private javax.swing.JButton buttonBuscarAuto;
    private javax.swing.JButton buttonBuscarVuelos;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelAlojamiento;
    private javax.swing.JPanel panelAutos;
    private javax.swing.JPanel panelMotorBusquedaAuto;
    private javax.swing.JPanel panelMotorBusquedaHotel;
    private javax.swing.JPanel panelMotorBusquedaVuelo;
    private javax.swing.JPanel panelOpcionesAvanzadaAlojamiento;
    private javax.swing.JPanel panelOpcionesAvanzadasAutos;
    private javax.swing.JPanel panelOpcionesAvanzadasVuelos;
    private javax.swing.JPanel panelResultadoAlojamiento;
    private javax.swing.JPanel panelResultadoAutos;
    private javax.swing.JPanel panelResultadoVuelo;
    private javax.swing.JPanel panelVuelo;
    private javax.swing.JToggleButton toggleButtonOpAvAlojamiento;
    private javax.swing.JToggleButton toggleButtonOpAvAuto;
    private javax.swing.JToggleButton toggleButtonOpcionesAvanzadasVuelo;
    // End of variables declaration//GEN-END:variables

    public boolean isBuscarVuelos() {
        return buscarVuelos;
    }

    public void setBuscarVuelos(boolean buscarVuelos) {
        this.buscarVuelos = buscarVuelos;
    }

    /**
     * @return the buscarAlojameinto
     */
    public boolean isBuscarAlojameinto() {
        return buscarAlojameinto;
    }

    /**
     * @param buscarAlojameinto the buscarAlojameinto to set
     */
    public void setBuscarAlojameinto(boolean buscarAlojameinto) {
        this.buscarAlojameinto = buscarAlojameinto;
    }

    /**
     * @return the buscarAuto
     */
    public boolean isBuscarAuto() {
        return buscarAuto;
    }

    /**
     * @param buscarAuto the buscarAuto to set
     */
    public void setBuscarAuto(boolean buscarAuto) {
        this.buscarAuto = buscarAuto;
    }

    /**
     * @return the jTabbedPane1
     */
    public javax.swing.JTabbedPane getJTabbedPane1() {
        return jTabbedPane1;
    }
}

