/*
 * PanelPropertyDatatype.java
 *
 * Created on 18 de agosto de 2008, 11:11
 */
package com.ontotravel.gui.panels.nuevaontologia;

import com.ontotravel.mvc.model.BusinessDelegate;
import com.ontotravel.util.Constantes;
import com.ontotravel.util.JListCellRenderer;
import com.ontotravel.util.JListItem;
import com.ontotravel.vo.DatatypePropertyVO;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;

/**
 *
 * @author  Administrador
 */
public class PanelPropertyDatatype extends javax.swing.JPanel {

    private PanelNuevaOntologia panel;
    private int varEnter;
    private DatatypePropertyVO propiedad;
    private String propertyDatatypeNameAux;

    /** Creates new form PanelPropertyDatatype */
    public PanelPropertyDatatype(PanelNuevaOntologia pan) {
        panel = pan;
        initComponents();
        initComponents2();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDomain = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        comboBoxRange = new javax.swing.JComboBox();
        buttonAddDomain = new javax.swing.JButton();
        buttonRemoveDomain = new javax.swing.JButton();

        jLabel1.setText("Property");

        textFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldNombreFocusLost(evt);
            }
        });
        textFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldNombreKeyTyped(evt);
            }
        });

        jLabel2.setText("Domain");

        listDomain.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listDomain);

        jLabel3.setText("Range");

        comboBoxRange.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "date", "string", "int", "float", "boolean" }));
        comboBoxRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRangeActionPerformed(evt);
            }
        });

        buttonAddDomain.setText("Ad");
        buttonAddDomain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddDomainActionPerformed(evt);
            }
        });

        buttonRemoveDomain.setText("Re");
        buttonRemoveDomain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveDomainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(69, 69, 69)
                        .addComponent(buttonAddDomain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRemoveDomain)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(comboBoxRange, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonAddDomain)
                        .addComponent(buttonRemoveDomain)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

//Aca falta agrega la forma de obtener el domain
private void buttonAddDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddDomainActionPerformed
        PanelDomain dom = new PanelDomain(true, panel.getMain(), true, panel, this);
        dom.setVisible(true);
}//GEN-LAST:event_buttonAddDomainActionPerformed

private void buttonRemoveDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveDomainActionPerformed
    //Remove domain
    String dom = listDomain.getSelectedValue().toString();
    ((BusinessDelegate) panel.getVistaNuevaOntologia().getModelo()).removeDomain(propiedad.getName(), dom);
    DefaultListModel mode = (DefaultListModel) listDomain.getModel();
    for (int i = 0; i < mode.size(); i++) {
        JListItem item = (JListItem) mode.get(i);
        if (item.getTitle().equals(dom)) {
            mode.removeElement(item);
        }
    }
}//GEN-LAST:event_buttonRemoveDomainActionPerformed

private void comboBoxRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRangeActionPerformed
    if (comboBoxRange.getSelectedIndex() != -1) {
        String name = comboBoxRange.getSelectedItem().toString();
        ((BusinessDelegate) panel.getVistaNuevaOntologia().getModelo()).changeRange(propiedad.getName(), name);
    }
}//GEN-LAST:event_comboBoxRangeActionPerformed

private void textFieldNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldNombreFocusGained
// Focus gained del text field del datatype property
    propertyDatatypeNameAux = textFieldNombre.getText();
    varEnter = 0;
}//GEN-LAST:event_textFieldNombreFocusGained

private void textFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldNombreFocusLost
    if (varEnter == 0) {
        cambiarNombrePropiedad();
    }
}//GEN-LAST:event_textFieldNombreFocusLost

private void textFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldNombreKeyTyped
    Character a = new Character(' ');
    if (a.equals(evt.getKeyChar())) {
        evt.setKeyChar('_');
        varEnter = 0;
    } else if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
        varEnter = 1;
        cambiarNombrePropiedad();
    } else {
        varEnter = 0;
    }
}//GEN-LAST:event_textFieldNombreKeyTyped

    public void cambiarNombrePropiedad() {
        if (!propertyDatatypeNameAux.equalsIgnoreCase(textFieldNombre.getText())) {
            String name = textFieldNombre.getText();
            if (!name.isEmpty()) {
                ((BusinessDelegate) panel.getVistaNuevaOntologia().getModelo()).changeNameDatatypeProperty(propertyDatatypeNameAux, name);
                DefaultListModel model = (DefaultListModel) panel.getListPropertiesDatatype().getModel();
                int index = model.indexOf(propertyDatatypeNameAux);
                model.remove(index);
                model.add(index, name);
                propiedad.setName(name);
                panel.getListPropertiesDatatype().setSelectedIndex(index);
            }
        }
    }

    public void addDomain(String name) {
        DefaultListModel model = (DefaultListModel) listDomain.getModel();
        if (!model.contains(name)) {
            ((BusinessDelegate) panel.getVistaNuevaOntologia().getModelo()).addDomain(propiedad.getName(), name);
            model.addElement(new JListItem(name, Constantes.ICONTREE));
        }
    }

    public void initComponents2() {
        listDomain.setModel(new DefaultListModel());
        listDomain.setCellRenderer(new JListCellRenderer());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddDomain;
    private javax.swing.JButton buttonRemoveDomain;
    private javax.swing.JComboBox comboBoxRange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listDomain;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox getComboBoxRange() {
        return comboBoxRange;
    }

    public void setComboBoxRange(javax.swing.JComboBox comboBoxRange) {
        this.comboBoxRange = comboBoxRange;
    }

    public javax.swing.JList getListDomain() {
        return listDomain;
    }

    public void setListDomain(javax.swing.JList listDomain) {
        this.listDomain = listDomain;
    }

    public javax.swing.JTextField getTextFieldNombre() {
        return textFieldNombre;
    }

    public void setTextFieldNombre(javax.swing.JTextField textFieldNombre) {
        this.textFieldNombre = textFieldNombre;
    }

    public DatatypePropertyVO getPropiedad() {
        return propiedad;
    }

    public void setPropiedad(DatatypePropertyVO propiedad) {
        this.propiedad = propiedad;
    }
}
