/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelString.java
 *
 * Created on 15/03/2009, 15:20:09
 */
package com.ontotravel.gui.panels.busqueda.tipodatoproavanzada;

import com.ontotravel.config.TipoDato;

/**
 *
 * @author Brunoli
 */
public class PanelAnyType extends javax.swing.JPanel implements PanelTipoDato {

    private TipoDato tipoDato;
    private boolean valido;
    private String nombrePropiedad;

    /** Creates new form PanelString */
    public PanelAnyType(String nombre, TipoDato tipoDato) {
        initComponents();
        this.nombrePropiedad = nombre;
        ponerNombre(nombre);
        this.labelError.setVisible(false);
        this.tfValor.setEnabled(false);
        this.tipoDato = tipoDato;
        this.valido = true;
    }

    private boolean comprobarTipo() {
        try {
            switch (tipoDato) {
                case ANY:
                    return true;
                case DOUBLE:
                    Double.parseDouble(tfValor.getText());
                    break;
                case FLOAT:
                    Float.parseFloat(tfValor.getText());
                    break;
                case INTEGER:
                    Integer.parseInt(tfValor.getText());
                    break;
                case STRING:
                    return true;
            }
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        labelError = new javax.swing.JLabel();
        cbEnabled = new javax.swing.JCheckBox();

        labelNombre.setText("Nombre:");
        labelNombre.setName("labelNombre"); // NOI18N

        tfValor.setName("tfValor"); // NOI18N
        tfValor.setPreferredSize(new java.awt.Dimension(100, 20));
        tfValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfValorKeyReleased(evt);
            }
        });

        labelError.setForeground(new java.awt.Color(255, 51, 51));
        labelError.setText("ERROR");
        labelError.setName("labelError"); // NOI18N

        cbEnabled.setName("cbEnabled"); // NOI18N
        cbEnabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnabledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbEnabled)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(cbEnabled)
                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelError))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ponerNombre(String nombre) {
        nombre = nombre.replace("_", " ");
        nombre += ":";
        labelNombre.setText(nombre);
    }

    private void tfValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorKeyReleased
        verificarInputTextField();
    }//GEN-LAST:event_tfValorKeyReleased

    private void cbEnabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnabledActionPerformed
        tfValor.setEnabled(cbEnabled.isSelected());
        if (!cbEnabled.isSelected()) {
            tfValor.setText("");
        }
    }//GEN-LAST:event_cbEnabledActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbEnabled;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getValue() {
        if (tfValor.getText().trim().isEmpty()) {
            return null;
        }
        return tfValor.getText();
    }

    private void verificarInputTextField() {
        String value = tfValor.getText();
        boolean result;
        if (!value.trim().isEmpty()) {
            result = comprobarTipo();
            if (result) {
                valido = true;
                labelError.setVisible(false);
            } else {
                valido = false;
                labelError.setVisible(true);
            }
        } else {
            valido = true;
            labelError.setVisible(false);
        }
    }

    @Override
    public boolean isActived() {
        return cbEnabled.isSelected();
    }

    @Override
    public boolean checkInput() {
        return valido;
    }

    @Override
    public void clearData() {
        labelError.setVisible(false);
        tfValor.setText("");
        cbEnabled.setSelected(false);
    }

    @Override
    public String getNombre() {
        return nombrePropiedad;
    }
}
