/*
 * PanelSinonimos.java
 *
 * Created on 31 de julio de 2008, 23:33
 */
package panels.sinonimos;

import gui.FileChooser;
import controladores.ControladorPanelSinonimos;
import gui.FramePrincipal;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import modelo.BusinessDelegate;
import varios.Constantes;
import vistas.VistaSinonimos;
import vo.IndividualSinonimoVO;

/**
 *
 * @author  Administrador
 */
public class PanelSinonimos extends javax.swing.JPanel {

    private FileChooser chooser;
    private FramePrincipal main;
    private VistaSinonimos vista;
    private String urlOWL;
    private String chooserButton;
    private boolean cargarArbol;
    private TreeSelectionEvent eventoTree;
    private boolean cargarInstancia;
    private boolean agregarSinonimo;
    private boolean agregarTraduccion;
    private boolean removerSinonimo;
    private boolean removerTraduccion;
    private int indexDefault = 0;
    private String sinoSelec;

    /** Creates new form PanelSinonimos */
    public PanelSinonimos(FramePrincipal main, VistaSinonimos vista) {
        this.main = main;
        this.vista = vista;
        initComponents();
        initComponents2();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldURL = new javax.swing.JTextField();
        buttonExaminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeIndividual = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonAddSinonimo = new javax.swing.JButton();
        buttonRemoveSinonimo = new javax.swing.JButton();
        buttonAddTraduccion = new javax.swing.JButton();
        buttonRemoveTraduccion = new javax.swing.JButton();
        labelPalabra = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSinonimos = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listTraduccion = new javax.swing.JList();
        panelAgregarSin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        textFieldAgregarSin = new javax.swing.JTextField();
        panelAgregarTraduccion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        textFieldAgregarTra = new javax.swing.JTextField();
        buttonGuardar = new javax.swing.JButton();
        panelAgregarPalabra = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfNombrePalabra = new javax.swing.JTextField();
        buttonAceptarPalabra = new javax.swing.JButton();
        buttonCancelarPalabra = new javax.swing.JButton();
        buttonAgregarPalabra = new javax.swing.JButton();
        buttonRemoverPalabra = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1023, 532));

        jLabel1.setText("Ontologia Vocabulario");

        buttonExaminar.setText("Examinar");
        buttonExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExaminarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(treeIndividual);

        jLabel2.setText("Palabra");

        jLabel3.setText("Sinonimo");

        jLabel4.setText("Traduccion");

        buttonAddSinonimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add_obj.gif"))); // NOI18N
        buttonAddSinonimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddSinonimoActionPerformed(evt);
            }
        });

        buttonRemoveSinonimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete_obj.gif"))); // NOI18N
        buttonRemoveSinonimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveSinonimoActionPerformed(evt);
            }
        });

        buttonAddTraduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add_obj.gif"))); // NOI18N
        buttonAddTraduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddTraduccionActionPerformed(evt);
            }
        });

        buttonRemoveTraduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete_obj.gif"))); // NOI18N
        buttonRemoveTraduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveTraduccionActionPerformed(evt);
            }
        });

        listSinonimos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listSinonimos);

        listTraduccion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listTraduccion);

        jLabel5.setText("Nombre");

        jButton1.setText("Ca");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        textFieldAgregarSin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldAgregarSinKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarSinLayout = new javax.swing.GroupLayout(panelAgregarSin);
        panelAgregarSin.setLayout(panelAgregarSinLayout);
        panelAgregarSinLayout.setHorizontalGroup(
            panelAgregarSinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarSinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldAgregarSin, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        panelAgregarSinLayout.setVerticalGroup(
            panelAgregarSinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarSinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAgregarSinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(textFieldAgregarSin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel6.setText("Nombre");

        jButton5.setText("Ok");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("Ca");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        textFieldAgregarTra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldAgregarTraKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarTraduccionLayout = new javax.swing.GroupLayout(panelAgregarTraduccion);
        panelAgregarTraduccion.setLayout(panelAgregarTraduccionLayout);
        panelAgregarTraduccionLayout.setHorizontalGroup(
            panelAgregarTraduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarTraduccionLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldAgregarTra, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
        panelAgregarTraduccionLayout.setVerticalGroup(
            panelAgregarTraduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarTraduccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarTraduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(textFieldAgregarTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addComponent(panelAgregarTraduccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(buttonAddSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonRemoveSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(panelAgregarSin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                        .addComponent(buttonAddTraduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRemoveTraduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelPalabra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonRemoveSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddSinonimo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(panelAgregarSin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonAddTraduccion)
                    .addComponent(buttonRemoveTraduccion)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAgregarTraduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGuardar.setText("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre");

        tfNombrePalabra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombrePalabraKeyTyped(evt);
            }
        });

        buttonAceptarPalabra.setText("A");
        buttonAceptarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptarPalabraActionPerformed(evt);
            }
        });

        buttonCancelarPalabra.setText("C");
        buttonCancelarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarPalabraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarPalabraLayout = new javax.swing.GroupLayout(panelAgregarPalabra);
        panelAgregarPalabra.setLayout(panelAgregarPalabraLayout);
        panelAgregarPalabraLayout.setHorizontalGroup(
            panelAgregarPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarPalabraLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(tfNombrePalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAceptarPalabra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCancelarPalabra))
        );
        panelAgregarPalabraLayout.setVerticalGroup(
            panelAgregarPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarPalabraLayout.createSequentialGroup()
                .addGroup(panelAgregarPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfNombrePalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAceptarPalabra)
                    .addComponent(buttonCancelarPalabra))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        buttonAgregarPalabra.setText("Add");
        buttonAgregarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarPalabraActionPerformed(evt);
            }
        });

        buttonRemoverPalabra.setText("Rem");
        buttonRemoverPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverPalabraActionPerformed(evt);
            }
        });

        jLabel7.setText("Palabra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonGuardar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(textFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonExaminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(buttonAgregarPalabra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonRemoverPalabra))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelAgregarPalabra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buttonExaminar)
                    .addComponent(textFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(buttonAgregarPalabra)
                            .addComponent(buttonRemoverPalabra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAgregarPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonGuardar)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

private void buttonExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExaminarActionPerformed
//Filechooser para elegir el archivo owl
    chooser = new FileChooser(main, true, main.getConfiguration().getOwlDirectory());
    setUrlOWL(chooser.getPath());
    setChooserButton(chooser.getButton());
    if (chooserButton.equals("Cancel")) {
    } else {
        // Cargar los table
        main.getConfiguration().setDefaultURLOWLSinonimos(chooser.getPath());
        textFieldURL.setText(chooser.getPath());
        ((ControladorPanelSinonimos) vista.getControlador()).doCargarOWL(true);
    }
}//GEN-LAST:event_buttonExaminarActionPerformed

    private void buttonCargarActionPerformed(javax.swing.event.TreeSelectionEvent evt) {
        // Cargar solicitud en tablas
        this.eventoTree = evt;
        if (!eventoTree.getPath().getLastPathComponent().toString().equals("Palabras")) {
            ((ControladorPanelSinonimos) vista.getControlador()).doCargarInstancia(true);
        }
    }

private void buttonAddSinonimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddSinonimoActionPerformed
    this.panelAgregarSin.setVisible(true);
}//GEN-LAST:event_buttonAddSinonimoActionPerformed

private void buttonAddTraduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddTraduccionActionPerformed
    this.panelAgregarTraduccion.setVisible(true);
}//GEN-LAST:event_buttonAddTraduccionActionPerformed

private void buttonRemoveSinonimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveSinonimoActionPerformed
    if (listSinonimos.getSelectedIndex() != -1) {
        ((ControladorPanelSinonimos) vista.getControlador()).doRemoverSinonimo(true);
    }
}//GEN-LAST:event_buttonRemoveSinonimoActionPerformed

private void buttonRemoveTraduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveTraduccionActionPerformed
    if (listTraduccion.getSelectedIndex() != -1) {
        ((ControladorPanelSinonimos) vista.getControlador()).doRemoverTraduccion(true);
    }
}//GEN-LAST:event_buttonRemoveTraduccionActionPerformed

private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
    ((BusinessDelegate) vista.getModelo()).guardarOntologiaSinonimos();
}//GEN-LAST:event_buttonGuardarActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    ((ControladorPanelSinonimos) vista.getControlador()).doAgregarSinonimo(true);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.textFieldAgregarSin.setText("");
    this.panelAgregarSin.setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    ((ControladorPanelSinonimos) vista.getControlador()).doAgregarTraduccion(true);
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    this.textFieldAgregarTra.setText("");
    this.panelAgregarTraduccion.setVisible(false);
}//GEN-LAST:event_jButton3ActionPerformed

private void buttonCancelarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarPalabraActionPerformed
    panelAgregarPalabra.setVisible(false);
    tfNombrePalabra.setText("");
}//GEN-LAST:event_buttonCancelarPalabraActionPerformed

private void buttonAgregarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarPalabraActionPerformed
    panelAgregarPalabra.setVisible(true);
}//GEN-LAST:event_buttonAgregarPalabraActionPerformed

private void buttonAceptarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptarPalabraActionPerformed
    String nombre = tfNombrePalabra.getText();
    nombre = nombre.trim();
    if(!nombre.isEmpty()){
        //Compruebo que ya no exista
        ArrayList<String> individuals = (ArrayList<String>) ((BusinessDelegate) vista.getModelo()).obtenerInstanciasVocabuario(urlOWL);
        if(!individuals.contains(nombre)){
            //No lo contiene entonces lo agrego
            ((BusinessDelegate) vista.getModelo()).agregarPalabra(nombre);
            //Ahora lo agrego al arbol
            cargarTree();
            ((BusinessDelegate) vista.getModelo()).guardarOntologiaSinonimos();
            this.invalidate();
            panelAgregarPalabra.setVisible(false);
            tfNombrePalabra.setText("");
        }else{
            JOptionPane.showMessageDialog(this,
                "Ya existe es palabra",
                "Asistente de Viajes",JOptionPane.INFORMATION_MESSAGE);
        }
    }
}//GEN-LAST:event_buttonAceptarPalabraActionPerformed

private void tfNombrePalabraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombrePalabraKeyTyped
    Character a = new Character( ' ' );
    if(a.equals(evt.getKeyChar())){
        evt.setKeyChar('_');
    }
}//GEN-LAST:event_tfNombrePalabraKeyTyped

private void textFieldAgregarSinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldAgregarSinKeyTyped
    Character a = new Character( ' ' );
    if(a.equals(evt.getKeyChar())){
        evt.setKeyChar('_');
    }
}//GEN-LAST:event_textFieldAgregarSinKeyTyped

private void textFieldAgregarTraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldAgregarTraKeyTyped
    Character a = new Character( ' ' );
    if(a.equals(evt.getKeyChar())){
        evt.setKeyChar('_');
    }
}//GEN-LAST:event_textFieldAgregarTraKeyTyped

private void buttonRemoverPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverPalabraActionPerformed
    String instancia = eventoTree.getPath().getLastPathComponent().toString();
    if (JOptionPane.showConfirmDialog(this,
                "Esta seguro que desea eliminar la palabra ' "+instancia+" '?",
                "Asistente de Viajes", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == 0) {
                ((BusinessDelegate) vista.getModelo()).removerPalabra(instancia);
                ((BusinessDelegate) vista.getModelo()).guardarOntologiaSinonimos();
                cargarTree();
    }
    
}//GEN-LAST:event_buttonRemoverPalabraActionPerformed

    public void update() {
        if (cargarArbol) {
            cargarTree();
            if (cargarInstancia) {
                cargarIndividualInPanel();
            } else {
                if (isAgregarSinonimo()) {
                    agregarSinonimo();
                } else if (isAgregarTraduccion()) {
                    agregarTraduccion();
                } else if (isRemoverSinonimo()) {
                    removerSinonimo();
                } else if (isRemoverTraduccion()) {
                    removerTraduccion();
                } else {
                }
            }
        } else {
        }
    }

    public void agregarSinonimo() {
        DefaultListModel model = (DefaultListModel) listSinonimos.getModel();
        model.addElement(new String(textFieldAgregarSin.getText()));
        String instancia = labelPalabra.getText();
        ((BusinessDelegate) vista.getModelo()).agregarSinonimo(instancia, textFieldAgregarSin.getText());
        textFieldAgregarSin.setText("");
        this.panelAgregarSin.setVisible(false);
    }

    public void agregarTraduccion() {
        DefaultListModel model = (DefaultListModel) listTraduccion.getModel();
        model.addElement(new String(textFieldAgregarTra.getText()));
        String instancia = labelPalabra.getText();
        ((BusinessDelegate) vista.getModelo()).agregarTraduccion(instancia, textFieldAgregarTra.getText());
        textFieldAgregarTra.setText("");
        this.panelAgregarTraduccion.setVisible(false);
    }

    public void removerSinonimo() {
        DefaultListModel model = (DefaultListModel) listSinonimos.getModel();
        String instancia = labelPalabra.getText();
        ((BusinessDelegate) vista.getModelo()).removerSinonimo(instancia, model.getElementAt(listSinonimos.getSelectedIndex()).toString());
        model.remove(listSinonimos.getSelectedIndex());
    }

    public void removerTraduccion() {
        DefaultListModel model = (DefaultListModel) listTraduccion.getModel();
        String instancia = labelPalabra.getText();
        ((BusinessDelegate) vista.getModelo()).removerTraduccion(instancia, model.getElementAt(listTraduccion.getSelectedIndex()).toString());
        model.remove(listTraduccion.getSelectedIndex());
    }

    public void cargarIndividualInPanel() {
        String instancia = eventoTree.getPath().getLastPathComponent().toString();
        IndividualSinonimoVO individual = (IndividualSinonimoVO) ((BusinessDelegate) vista.getModelo()).obtenerIndividual(instancia);
        ArrayList<String> sinonimos = individual.getSinonimos();
        ArrayList<String> traduccion = individual.getTraduccion();
        String nombre = individual.getNombreInstancia();
        labelPalabra.setText(nombre);
        listSinonimos.setModel(new DefaultListModel());
        DefaultListModel dlm = (DefaultListModel) listSinonimos.getModel();

        Iterator itSin = sinonimos.iterator();
        while (itSin.hasNext()) {
            dlm.addElement(itSin.next().toString());
        }

        listTraduccion.setModel(new DefaultListModel());
        DefaultListModel dlm2 = (DefaultListModel) listTraduccion.getModel();
        Iterator itTra = traduccion.iterator();
        while (itTra.hasNext()) {
            dlm2.addElement(itTra.next().toString());
        }
    }

    public void cargarTree() {
        ArrayList<String> individuals = (ArrayList<String>) ((BusinessDelegate) vista.getModelo()).obtenerInstanciasVocabuario(urlOWL);

        DefaultMutableTreeNode abuelo = new DefaultMutableTreeNode("Palabras");
        DefaultTreeModel modelo = new DefaultTreeModel(abuelo);
        treeIndividual = new JTree(modelo);
        DefaultMutableTreeNode[] padre = new DefaultMutableTreeNode[individuals.size()];
        Iterator it = individuals.iterator();
        int i = 0;
        while (it.hasNext()) {
            padre[i] = new DefaultMutableTreeNode(it.next().toString());
            i++;
        }
        for (int j = 0; j < padre.length; j++) {
            modelo.insertNodeInto(padre[j], abuelo, j);
        }
        treeIndividual.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {

            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                buttonCargarActionPerformed(evt);
            }
        });
        ImageIcon leafIcon = new ImageIcon(Constantes.ICONINDIVIDUAL);
        if (leafIcon != null) {
            DefaultTreeCellRenderer renderer =
                    new DefaultTreeCellRenderer();
            renderer.setOpenIcon(leafIcon);
            renderer.setClosedIcon(leafIcon);
            renderer.setLeafIcon(leafIcon);
            treeIndividual.setCellRenderer(renderer);
            jScrollPane1.setViewportView(treeIndividual);
        }
        Object root = treeIndividual.getModel().getRoot();
        TreePath path = new TreePath(root);
        treeIndividual.expandPath(path);
    }

    public void setCargarArbol(boolean flag) {
        this.cargarArbol = flag;
    }

    private void initComponents2() {
        DefaultMutableTreeNode abuelo = new DefaultMutableTreeNode("Palabras");
        DefaultTreeModel modelo = new DefaultTreeModel(abuelo);
        treeIndividual = new JTree(modelo);

        ImageIcon leafIcon = new ImageIcon(Constantes.ICONINDIVIDUAL);
        if (leafIcon != null) {
            DefaultTreeCellRenderer renderer =
                    new DefaultTreeCellRenderer();
            renderer.setOpenIcon(leafIcon);
            renderer.setClosedIcon(leafIcon);
            renderer.setLeafIcon(leafIcon);
            treeIndividual.setCellRenderer(renderer);
            jScrollPane1.setViewportView(treeIndividual);
        }

        panelAgregarPalabra.setVisible(false);
        //Crear lista mutable sinonimos

        listSinonimos.setVisibleRowCount(-1);

        //Crear lista mutable traduccion

        listTraduccion.setVisibleRowCount(-1);

        panelAgregarSin.setVisible(false);
        panelAgregarTraduccion.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAceptarPalabra;
    private javax.swing.JButton buttonAddSinonimo;
    private javax.swing.JButton buttonAddTraduccion;
    private javax.swing.JButton buttonAgregarPalabra;
    private javax.swing.JButton buttonCancelarPalabra;
    private javax.swing.JButton buttonExaminar;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonRemoveSinonimo;
    private javax.swing.JButton buttonRemoveTraduccion;
    private javax.swing.JButton buttonRemoverPalabra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelPalabra;
    private javax.swing.JList listSinonimos;
    private javax.swing.JList listTraduccion;
    private javax.swing.JPanel panelAgregarPalabra;
    private javax.swing.JPanel panelAgregarSin;
    private javax.swing.JPanel panelAgregarTraduccion;
    private javax.swing.JTextField textFieldAgregarSin;
    private javax.swing.JTextField textFieldAgregarTra;
    private javax.swing.JTextField textFieldURL;
    private javax.swing.JTextField tfNombrePalabra;
    private javax.swing.JTree treeIndividual;
    // End of variables declaration//GEN-END:variables

    public String getUrlOWL() {
        return urlOWL;
    }

    public void setUrlOWL(String urlOWL) {
        this.urlOWL = urlOWL;
    }

    public String getChooserButton() {
        return chooserButton;
    }

    public void setChooserButton(String chooserButton) {
        this.chooserButton = chooserButton;
    }

    public boolean isCargarInstancia() {
        return cargarInstancia;
    }

    public void setCargarInstancia(boolean cargarInstancia) {
        this.cargarInstancia = cargarInstancia;
    }

    public boolean isAgregarSinonimo() {
        return agregarSinonimo;
    }

    public void setAgregarSinonimo(boolean agregarSinonimo) {
        this.agregarSinonimo = agregarSinonimo;
    }

    public boolean isAgregarTraduccion() {
        return agregarTraduccion;
    }

    public void setAgregarTraduccion(boolean agregarTraduccion) {
        this.agregarTraduccion = agregarTraduccion;
    }

    public boolean isRemoverSinonimo() {
        return removerSinonimo;
    }

    public void setRemoverSinonimo(boolean removerSinonimo) {
        this.removerSinonimo = removerSinonimo;
    }

    public boolean isRemoverTraduccion() {
        return removerTraduccion;
    }

    public void setRemoverTraduccion(boolean removerTraduccion) {
        this.removerTraduccion = removerTraduccion;
    }
}
