/*
 * PanelNuevaOntologia.java
 *
 * Created on 18 de agosto de 2008, 10:02
 */

package panels.nuevaontologia;


import controladores.ControladorPanelNuevaOntologia;
import gui.FramePrincipal;
import java.awt.Toolkit;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map.Entry;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreePath;
import modelo.BusinessDelegate;
import varios.Constantes;
import vistas.VistaNuevaOntologia;
import vo.DatatypePropertyVO;
import vo.ObjectPropertyVO;

/**
 *
 * @author  Administrador
 */
public class PanelNuevaOntologia extends javax.swing.JPanel {

    private FramePrincipal main;
    private VistaNuevaOntologia vistaNuevaOntologia;
    private String urlOWL;
    private String chooserButton;
    private boolean cargarOntologia;
    private boolean nuevaOntologia;
    private boolean cargarClase;
    private boolean cargarObjectProperty;
    private boolean cargarDatatypeProperty;
    private TreeSelectionEvent eventoTree;
    private DefaultTreeModel modelo;
    private DefaultMutableTreeNode abuelo;
    private Toolkit toolkit = Toolkit.getDefaultToolkit();
    private HashMap<String,DefaultMutableTreeNode> mapaNodos;
    
    /** Creates new form PanelNuevaOntologia */
    public PanelNuevaOntologia(FramePrincipal ref, VistaNuevaOntologia vistaN) {
        this.main = ref;
        this.vistaNuevaOntologia = vistaN;
        initComponents();
        initComponents2();
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelMetadata = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldURI = new javax.swing.JTextField();
        panelClasses = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeClasses = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        listProperties = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        textFieldClassName = new javax.swing.JTextField();
        buttonRemoverClass = new javax.swing.JButton();
        buttonAgregarClass = new javax.swing.JButton();
        panelAgregarNombre = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        textFieldNombreClase = new javax.swing.JTextField();
        buttonOkNombre = new javax.swing.JButton();
        buttonCancelNombre = new javax.swing.JButton();
        panelProperties = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelTabbedObjectProperty = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listPropertiesObject = new javax.swing.JList();
        panelTabbedDatatypeProperty = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listPropertiesDatatype = new javax.swing.JList();
        panelPropertyDefault = new javax.swing.JPanel();
        panelIndividuals = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        treeClasses2 = new javax.swing.JTree();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        listIndividuals = new javax.swing.JList();
        panelIndividualData = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        textFieldNombreIndividual = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        panelIndividualProperties = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1023, 532));

        jLabel1.setText("Ontology URI");

        javax.swing.GroupLayout panelMetadataLayout = new javax.swing.GroupLayout(panelMetadata);
        panelMetadata.setLayout(panelMetadataLayout);
        panelMetadataLayout.setHorizontalGroup(
            panelMetadataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMetadataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMetadataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldURI, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(591, Short.MAX_VALUE))
        );
        panelMetadataLayout.setVerticalGroup(
            panelMetadataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMetadataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldURI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Metadata", panelMetadata);

        jScrollPane1.setViewportView(treeClasses);

        listProperties.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listProperties);

        jLabel2.setText("Hierarchy");

        jLabel3.setText("Properties");

        jButton1.setText("Remove");

        jButton2.setText("Create OP");

        jButton3.setText("Add P");

        jButton4.setText("Create DP");

        jLabel4.setText("Class");

        buttonRemoverClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/protege/class.delete.gif"))); // NOI18N
        buttonRemoverClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverClassActionPerformed(evt);
            }
        });

        buttonAgregarClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/protege/class.create.gif"))); // NOI18N
        buttonAgregarClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarClassActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre");

        buttonOkNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/protege/ok.gif"))); // NOI18N
        buttonOkNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkNombreActionPerformed(evt);
            }
        });

        buttonCancelNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/protege/cancel.gif"))); // NOI18N
        buttonCancelNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarNombreLayout = new javax.swing.GroupLayout(panelAgregarNombre);
        panelAgregarNombre.setLayout(panelAgregarNombreLayout);
        panelAgregarNombreLayout.setHorizontalGroup(
            panelAgregarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarNombreLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(14, 14, 14)
                .addComponent(textFieldNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOkNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCancelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        panelAgregarNombreLayout.setVerticalGroup(
            panelAgregarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarNombreLayout.createSequentialGroup()
                .addGroup(panelAgregarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(buttonOkNombre))
                    .addComponent(buttonCancelNombre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelClassesLayout = new javax.swing.GroupLayout(panelClasses);
        panelClasses.setLayout(panelClassesLayout);
        panelClassesLayout.setHorizontalGroup(
            panelClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClassesLayout.createSequentialGroup()
                .addGroup(panelClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClassesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAgregarClass, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRemoverClass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClassesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(panelClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelClassesLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(34, 34, 34)
                                    .addComponent(textFieldClassName))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelClassesLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(58, 58, 58)
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton4)
                                    .addGap(6, 6, 6)
                                    .addComponent(jButton3)
                                    .addGap(6, 6, 6)
                                    .addComponent(jButton1)))))
                    .addGroup(panelClassesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(panelAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        panelClassesLayout.setVerticalGroup(
            panelClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClassesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buttonAgregarClass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonRemoverClass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addGroup(panelClassesLayout.createSequentialGroup()
                        .addGroup(panelClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textFieldClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(panelClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Classes", panelClasses);

        jLabel5.setText("Object Properties");

        listPropertiesObject.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listPropertiesObject.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPropertiesObjectValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listPropertiesObject);

        javax.swing.GroupLayout panelTabbedObjectPropertyLayout = new javax.swing.GroupLayout(panelTabbedObjectProperty);
        panelTabbedObjectProperty.setLayout(panelTabbedObjectPropertyLayout);
        panelTabbedObjectPropertyLayout.setHorizontalGroup(
            panelTabbedObjectPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabbedObjectPropertyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTabbedObjectPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );
        panelTabbedObjectPropertyLayout.setVerticalGroup(
            panelTabbedObjectPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabbedObjectPropertyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Object", panelTabbedObjectProperty);

        jLabel6.setText("Datatype properties");

        listPropertiesDatatype.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listPropertiesDatatype.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPropertiesDatatypeValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(listPropertiesDatatype);

        javax.swing.GroupLayout panelTabbedDatatypePropertyLayout = new javax.swing.GroupLayout(panelTabbedDatatypeProperty);
        panelTabbedDatatypeProperty.setLayout(panelTabbedDatatypePropertyLayout);
        panelTabbedDatatypePropertyLayout.setHorizontalGroup(
            panelTabbedDatatypePropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabbedDatatypePropertyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTabbedDatatypePropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );
        panelTabbedDatatypePropertyLayout.setVerticalGroup(
            panelTabbedDatatypePropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabbedDatatypePropertyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Datatype", panelTabbedDatatypeProperty);

        panelPropertyDefault.setPreferredSize(new java.awt.Dimension(200, 100));
        panelPropertyDefault.setLayout(new java.awt.GridLayout(0, 1));

        javax.swing.GroupLayout panelPropertiesLayout = new javax.swing.GroupLayout(panelProperties);
        panelProperties.setLayout(panelPropertiesLayout);
        panelPropertiesLayout.setHorizontalGroup(
            panelPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPropertiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPropertyDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelPropertiesLayout.setVerticalGroup(
            panelPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPropertiesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelPropertyDefault, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Properties", panelProperties);

        jScrollPane5.setViewportView(treeClasses2);

        jLabel8.setText("Hierarchy");

        jLabel9.setText("Individuals");

        listIndividuals.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(listIndividuals);

        jLabel10.setText("Individual");

        panelIndividualProperties.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane7.setViewportView(panelIndividualProperties);

        javax.swing.GroupLayout panelIndividualDataLayout = new javax.swing.GroupLayout(panelIndividualData);
        panelIndividualData.setLayout(panelIndividualDataLayout);
        panelIndividualDataLayout.setHorizontalGroup(
            panelIndividualDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIndividualDataLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelIndividualDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIndividualDataLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(50, 50, 50)
                        .addComponent(textFieldNombreIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelIndividualDataLayout.setVerticalGroup(
            panelIndividualDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIndividualDataLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelIndividualDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNombreIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelIndividualsLayout = new javax.swing.GroupLayout(panelIndividuals);
        panelIndividuals.setLayout(panelIndividualsLayout);
        panelIndividualsLayout.setHorizontalGroup(
            panelIndividualsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIndividualsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelIndividualsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelIndividualsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIndividualsLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(panelIndividualData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(panelIndividualsLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(603, Short.MAX_VALUE))))
        );
        panelIndividualsLayout.setVerticalGroup(
            panelIndividualsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIndividualsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIndividualsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIndividualData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelIndividualsLayout.createSequentialGroup()
                        .addGroup(panelIndividualsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(15, 15, 15)
                        .addGroup(panelIndividualsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Individuals", panelIndividuals);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
private void initComponents2(){
    panelAgregarNombre.setVisible(false);
    mapaNodos = new HashMap<String, DefaultMutableTreeNode>();
    
    ImageIcon leafIcon = new ImageIcon("iconos/protege/TreeBold.gif");
    if (leafIcon != null) {
        DefaultTreeCellRenderer renderer = 
            new DefaultTreeCellRenderer();
        renderer.setLeafIcon(leafIcon);
        treeClasses.setCellRenderer(renderer);
    }

    setCargarClase(false);
    setCargarDatatypeProperty(false);
    setCargarObjectProperty(false);
    setCargarOntologia(false);
    setNuevaOntologia(false);
}

public void modoCargar(){
    ((ControladorPanelNuevaOntologia) vistaNuevaOntologia.getControlador()).doCargarOWL(true);
}

public void modoNuevo(){
    ((ControladorPanelNuevaOntologia) vistaNuevaOntologia.getControlador()).doNuevaOWL(true);
}

public void nuevaOntologia(){
    ((BusinessDelegate) vistaNuevaOntologia.getModelo()).nuevaOntologia();
}

public void cargarOntologia(){
    ((BusinessDelegate) vistaNuevaOntologia.getModelo()).cargarOntologia(getUrlOWL());       
}

public void guardarOntologia(){
    //Grabar ontologia
    ((BusinessDelegate)vistaNuevaOntologia.getModelo()).grabarOntologia(urlOWL);
}

public void update() {
    if(nuevaOntologia){
        vaciarPaneles();
        nuevaOntologia();
        cargarOntologiaDefault();
    }
    if(cargarOntologia){
        vaciarPaneles();
        cargarOntologia();
        cargarPaneles();
    }
    if(isCargarClase()){
        cargarClase();
    }
    if(isCargarDatatypeProperty()){
        cargarDatatypeProperty();
    }
    if(isCargarObjectProperty()){
        cargarObjectProperty();
    }
}



private void buttonAgregarClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarClassActionPerformed
// TODO add your handling code here:
    panelAgregarNombre.setVisible(true);
    
}//GEN-LAST:event_buttonAgregarClassActionPerformed

private void buttonRemoverClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverClassActionPerformed
// TODO add your handling code here:
    panelAgregarNombre.setVisible(false);
    removeCurrentNode();
}//GEN-LAST:event_buttonRemoverClassActionPerformed

private void buttonOkNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkNombreActionPerformed
// TODO add your handling code here:
    if(!mapaNodos.containsKey(textFieldNombreClase.getText())){
        addObject(textFieldNombreClase.getText());
        textFieldNombreClase.setText("");
        panelAgregarNombre.setVisible(false);
    }else{
        textFieldNombreClase.setText("");
        JOptionPane.showMessageDialog(this,"Clase Existente",Constantes.APPLICATION_NAME,JOptionPane.ERROR_MESSAGE);
    }
    
}//GEN-LAST:event_buttonOkNombreActionPerformed

private void buttonCancelNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelNombreActionPerformed
// TODO add your handling code here:
    textFieldNombreClase.setText("");
    panelAgregarNombre.setVisible(false);
}//GEN-LAST:event_buttonCancelNombreActionPerformed

private void listPropertiesObjectValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPropertiesObjectValueChanged
// Se selecciono un object propiedad en el panel de propiedades
    ((ControladorPanelNuevaOntologia) vistaNuevaOntologia.getControlador()).doCargarObjectProperty(true);
}//GEN-LAST:event_listPropertiesObjectValueChanged

private void listPropertiesDatatypeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPropertiesDatatypeValueChanged
// Se selecciono un datatype propiedad en el panel de propiedades
    ((ControladorPanelNuevaOntologia) vistaNuevaOntologia.getControlador()).doCargarDatatypeProperty(true);
}//GEN-LAST:event_listPropertiesDatatypeValueChanged

private void buttonCargarActionPerformed(javax.swing.event.TreeSelectionEvent evt) {
    this.eventoTree = evt;
    if(!eventoTree.getPath().getLastPathComponent().toString().equals("Classes")){
            ((ControladorPanelNuevaOntologia) vistaNuevaOntologia.getControlador()).doCargarClase(true);
    }
}

private void buttonCargarInstanciasActionPerformed(javax.swing.event.TreeSelectionEvent evt) {
    this.eventoTree = evt;
    if(!eventoTree.getPath().getLastPathComponent().toString().equals("Classes")){

    }
}

private void cargarPaneles(){
   cargarPanelMetadata();
   cargarPanelClases();
   cargarPanelProperty();
   cargarPanelInstancia();
}

private void cargarPanelMetadata(){
    String uri = ((BusinessDelegate)vistaNuevaOntologia.getModelo()).getURIOntologia();
    this.getTextFieldURI().setText(uri);
}

private void cargarPanelClases(){
    // Vaciar arbol
    
    
    abuelo = new DefaultMutableTreeNode("Classes");
    modelo = new DefaultTreeModel(abuelo);
    treeClasses = new JTree(modelo);
    
    HashMap<String,String> mapaClases = ((BusinessDelegate)vistaNuevaOntologia.getModelo()).showClasses();
    
    Set<Entry<String,String>> setClases = mapaClases.entrySet();
    Iterator itClases = setClases.iterator();
    DefaultMutableTreeNode node = null;
    while(itClases.hasNext()){
        Entry<String,String> clase = (Entry<String, String>) itClases.next();
        node = new DefaultMutableTreeNode(clase.getKey());
        mapaNodos.put(clase.getKey(), node);
    }
    itClases = setClases.iterator();
    while(itClases.hasNext()){
        Entry<String,String> clase = (Entry<String, String>) itClases.next();
        if(clase.getValue().isEmpty()){
            abuelo.add(mapaNodos.get(clase.getKey()));
        }else{
            mapaNodos.get(clase.getValue()).add(mapaNodos.get(clase.getKey()));
        }
    }
    treeClasses.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
    public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
            buttonCargarActionPerformed(evt);    
    }
    });
    jScrollPane1.setViewportView(treeClasses);
    Object root = treeClasses.getModel().getRoot();
    TreePath path = new TreePath(root);
    treeClasses.expandPath(path);
    ImageIcon leafIcon = createImageIcon("/iconos/protege/TreeBold.gif");
    if (leafIcon != null) {
        DefaultTreeCellRenderer renderer = new DefaultTreeCellRenderer();
        renderer.setLeafIcon(leafIcon);
        treeClasses.setCellRenderer(renderer);
    }
}





private void cargarPanelProperty(){
    List<String> datatypeProperties = ((BusinessDelegate)vistaNuevaOntologia.getModelo()).showDatatypeProperties();
    List<String> objectProperties = ((BusinessDelegate)vistaNuevaOntologia.getModelo()).showObjectProperties();
    
    listPropertiesDatatype.removeAll();
    listPropertiesObject.removeAll();
    
    
    listPropertiesDatatype.setModel(new DefaultListModel());
    listPropertiesObject.setModel(new DefaultListModel());
    
    DefaultListModel model1 = (DefaultListModel) listPropertiesDatatype.getModel();
    DefaultListModel model2 = (DefaultListModel) listPropertiesObject.getModel();
    
    for(int i = 0 ; i < datatypeProperties.size() ; i++){
        model1.addElement(datatypeProperties.get(i));
    }
    for(int i = 0 ; i < objectProperties.size() ; i++){
        model2.addElement(objectProperties.get(i));
    }
    
    listPropertiesDatatype.setModel(model1);
    listPropertiesObject.setModel(model2);
}

private void cargarPanelInstancia(){
    //Cargar Arbol
    treeClasses2 = new JTree(modelo);
    treeClasses2.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
    public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
            buttonCargarInstanciasActionPerformed(evt);    
    }
    });
    jScrollPane5.setViewportView(treeClasses2);
    Object root = treeClasses2.getModel().getRoot();
    TreePath path = new TreePath(root);
    treeClasses2.expandPath(path);
    ImageIcon leafIcon = createImageIcon("/iconos/protege/TreeBold.gif");
    if (leafIcon != null) {
        DefaultTreeCellRenderer renderer = new DefaultTreeCellRenderer();
        renderer.setLeafIcon(leafIcon);
        treeClasses2.setCellRenderer(renderer);
    }
}


public void cargarDatatypeProperty(){
    panelPropertyDefault.removeAll();
    PanelPropertyDatatype panel = new PanelPropertyDatatype();
    String propiedad = listPropertiesDatatype.getSelectedValue().toString();
    DatatypePropertyVO propiedades = ((BusinessDelegate)vistaNuevaOntologia.getModelo()).getDatatypeProperty(propiedad);
    panel.getTextFieldNombre().setText(propiedades.getName());
    DefaultListModel model = (DefaultListModel) panel.getListDomain().getModel();
    for(int i = 0 ; i < propiedades.getDomain().size() ; i++){
        model.addElement(propiedades.getDomain().get(i));
    }
    panel.getListDomain().setModel(model);
    String range = propiedades.getRange();
    panel.getComboBoxRange().setSelectedItem(range);
    
    panelPropertyDefault.add(panel);
}

public void cargarObjectProperty(){
    panelPropertyDefault.removeAll();
    PanelPropertyObject panel = new PanelPropertyObject();
    String propiedad = listPropertiesObject.getSelectedValue().toString();
    ObjectPropertyVO propiedades = ((BusinessDelegate)vistaNuevaOntologia.getModelo()).getObjectProperty(propiedad);
    panel.getTextFieldNombre().setText(propiedades.getName());
    DefaultListModel model = (DefaultListModel) panel.getListDomain().getModel();
    for(int i = 0 ; i < propiedades.getDomain().size() ; i++){
        model.addElement(propiedades.getDomain().get(i));
    }
    panel.getListDomain().setModel(model);
    DefaultListModel model2 = (DefaultListModel) panel.getListRange().getModel();
    for(int i = 0 ; i < propiedades.getRange().size() ; i++){
        model2.addElement(propiedades.getRange().get(i));
    }
    panel.getListRange().setModel(model2);
    
    panelPropertyDefault.add(panel);
}

public void cargarClase(){
    String instancia = treeClasses.getSelectionPath().getLastPathComponent().toString();
    List<String> propiedades = ((BusinessDelegate)vistaNuevaOntologia.getModelo()).ClassProperty(instancia);
    listProperties.removeAll();
    listProperties.setModel(new DefaultListModel());
    DefaultListModel model = ((DefaultListModel)listProperties.getModel());
    for(int i = 0 ; i < propiedades.size() ; i++){
        model.addElement(propiedades.get(i));
    }
    listProperties.setModel(model);
}


public void cargarOntologiaDefault(){
    cargarPanelMetadata();
    cargarPanelClases();
    cargarPanelProperty();
}


public void vaciarPaneles(){
    textFieldURI.setText("");
    textFieldNombreClase.setText("");
    treeClasses.setModel(new DefaultTreeModel(abuelo));
    treeClasses2.setModel(new DefaultTreeModel(abuelo));
    textFieldClassName.setText("");
    listProperties.setModel(new DefaultListModel());
    listPropertiesDatatype.setModel(new DefaultListModel());
    listPropertiesObject.setModel(new DefaultListModel());
    panelPropertyDefault.removeAll();
    listIndividuals.setModel(new DefaultListModel());
    textFieldNombreIndividual.setText("");
    panelIndividualProperties.removeAll();
    this.repaint();
}

//Uso Interno

private DefaultMutableTreeNode addObject(Object child) {
        DefaultMutableTreeNode parentNode = null;
        TreePath parentPath = treeClasses.getSelectionPath();
        
        if (parentPath == null) {
            parentNode = abuelo;
        } else {
            parentNode = (DefaultMutableTreeNode)
                         (parentPath.getLastPathComponent());
        }

        return addObject(parentNode, child, true);
}

private DefaultMutableTreeNode addObject(DefaultMutableTreeNode parent,
                                            Object child, 
                                            boolean shouldBeVisible) {
        DefaultMutableTreeNode childNode = 
                new DefaultMutableTreeNode(child);

        if (parent == null) {
            parent = abuelo;
        }
	
	//It is key to invoke this on the TreeModel, and NOT DefaultMutableTreeNode
        modelo.insertNodeInto(childNode, parent, 
                                 parent.getChildCount());
        mapaNodos.put(childNode.getUserObject().toString(), childNode);
        String hijo = childNode.getUserObject().toString();
        String padre = parent.getUserObject().toString();
        ((BusinessDelegate)vistaNuevaOntologia.getModelo()).addClass(hijo,padre);
        //Make sure the user can see the lovely new node.
        if (shouldBeVisible) {
            treeClasses.scrollPathToVisible(new TreePath(childNode.getPath()));
        }
        return childNode;
}

private void removeCurrentNode() {
        TreePath currentSelection = treeClasses.getSelectionPath();
        if (currentSelection != null) {
            DefaultMutableTreeNode currentNode = (DefaultMutableTreeNode)
                         (currentSelection.getLastPathComponent());
            MutableTreeNode parent = (MutableTreeNode)(currentNode.getParent());
            if (parent != null) {
                modelo.removeNodeFromParent(currentNode);
                mapaNodos.remove(currentNode.getUserObject().toString());
                return;
            }
        } 

        // Either there was no selection, or the root was selected.
        toolkit.beep();
}

protected static ImageIcon createImageIcon(String path) {
    java.net.URL imgURL = PanelNuevaOntologia.class.getResource(path);
    if (imgURL != null) {
        return new ImageIcon(imgURL);
    } else {
        System.err.println("Couldn't find file: " + path);
        return null;
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregarClass;
    private javax.swing.JButton buttonCancelNombre;
    private javax.swing.JButton buttonOkNombre;
    private javax.swing.JButton buttonRemoverClass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JList listIndividuals;
    private javax.swing.JList listProperties;
    private javax.swing.JList listPropertiesDatatype;
    private javax.swing.JList listPropertiesObject;
    private javax.swing.JPanel panelAgregarNombre;
    private javax.swing.JPanel panelClasses;
    private javax.swing.JPanel panelIndividualData;
    private javax.swing.JPanel panelIndividualProperties;
    private javax.swing.JPanel panelIndividuals;
    private javax.swing.JPanel panelMetadata;
    private javax.swing.JPanel panelProperties;
    private javax.swing.JPanel panelPropertyDefault;
    private javax.swing.JPanel panelTabbedDatatypeProperty;
    private javax.swing.JPanel panelTabbedObjectProperty;
    private javax.swing.JTextField textFieldClassName;
    private javax.swing.JTextField textFieldNombreClase;
    private javax.swing.JTextField textFieldNombreIndividual;
    private javax.swing.JTextField textFieldURI;
    private javax.swing.JTree treeClasses;
    private javax.swing.JTree treeClasses2;
    // End of variables declaration//GEN-END:variables

    public String getUrlOWL() {
        return urlOWL;
    }

    public void setUrlOWL(String urlOWL) {
        this.urlOWL = urlOWL;
    }

    public String getChooserButton() {
        return chooserButton;
    }

    public void setChooserButton(String chooserButton) {
        this.chooserButton = chooserButton;
    }

    public boolean isCargarOntologia() {
        return cargarOntologia;
    }

    public void setCargarOntologia(boolean cargarOntologia) {
        this.cargarOntologia = cargarOntologia;
    }

    public boolean isNuevaOntologia() {
        return nuevaOntologia;
    }

    public void setNuevaOntologia(boolean nuevaOntologia) {
        this.nuevaOntologia = nuevaOntologia;
    }

    public javax.swing.JTextField getTextFieldURI() {
        return textFieldURI;
    }

    public void setTextFieldURI(javax.swing.JTextField textFieldURI) {
        this.textFieldURI = textFieldURI;
    }

    public boolean isCargarClase() {
        return cargarClase;
    }

    public void setCargarClase(boolean cargarClase) {
        this.cargarClase = cargarClase;
    }

    public boolean isCargarObjectProperty() {
        return cargarObjectProperty;
    }

    public void setCargarObjectProperty(boolean cargarObjectProperty) {
        this.cargarObjectProperty = cargarObjectProperty;
    }

    public boolean isCargarDatatypeProperty() {
        return cargarDatatypeProperty;
    }

    public void setCargarDatatypeProperty(boolean cargarDatatypeProperty) {
        this.cargarDatatypeProperty = cargarDatatypeProperty;
    }

}
