/*
 * PanelPropertyDatatype.java
 *
 * Created on 18 de agosto de 2008, 11:11
 */

package panels.nuevaontologia;

import javax.swing.DefaultListModel;
import modelo.BusinessDelegate;
import vo.DatatypePropertyVO;

/**
 *
 * @author  Administrador
 */
public class PanelPropertyDatatype extends javax.swing.JPanel {

    private PanelNuevaOntologia panel;
    private DatatypePropertyVO propiedad;
    
    /** Creates new form PanelPropertyDatatype */
    public PanelPropertyDatatype(PanelNuevaOntologia pan) {
        panel = pan;
        initComponents();
        initComponents2();
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDomain = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        comboBoxRange = new javax.swing.JComboBox();
        buttonAddDomain = new javax.swing.JButton();
        buttonRemoveDomain = new javax.swing.JButton();
        buttonChangeName = new javax.swing.JButton();

        jLabel1.setText("Property");

        jLabel2.setText("Domain");

        listDomain.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listDomain);

        jLabel3.setText("Range");

        comboBoxRange.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "date", "string", "int", "double", "float", "boolean" }));
        comboBoxRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRangeActionPerformed(evt);
            }
        });

        buttonAddDomain.setText("Ad");
        buttonAddDomain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddDomainActionPerformed(evt);
            }
        });

        buttonRemoveDomain.setText("Re");
        buttonRemoveDomain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveDomainActionPerformed(evt);
            }
        });

        buttonChangeName.setText("Ch");
        buttonChangeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(69, 69, 69)
                        .addComponent(buttonAddDomain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonRemoveDomain)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(comboBoxRange, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonChangeName))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonChangeName))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonAddDomain)
                        .addComponent(buttonRemoveDomain)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(184, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
    }// </editor-fold>//GEN-END:initComponents

private void buttonChangeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangeNameActionPerformed
    String name = textFieldNombre.getText();
    if(!name.isEmpty()){
        String oldName = propiedad.getName();
        ((BusinessDelegate)panel.getVistaNuevaOntologia().getModelo()).changeNameObjectProperty(oldName,name);
        DefaultListModel model = (DefaultListModel) panel.getListPropertiesDatatype().getModel();
        int index = model.indexOf(oldName);
        model.remove(index);
        model.add(index, name);
        propiedad.setName(name);
    }
}//GEN-LAST:event_buttonChangeNameActionPerformed

//Aca falta agrega la forma de obtener el domain
private void buttonAddDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddDomainActionPerformed
    PanelDomain dom = new PanelDomain(true,panel.getMain(), true, panel, this);
    dom.setVisible(true);
}//GEN-LAST:event_buttonAddDomainActionPerformed

private void buttonRemoveDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveDomainActionPerformed
    //Remove domain
    String dom = listDomain.getSelectedValue().toString();
    ((BusinessDelegate)panel.getVistaNuevaOntologia().getModelo()).removeDomain(propiedad.getName(),dom);
    DefaultListModel mode = (DefaultListModel) listDomain.getModel();
    mode.removeElement(dom);
}//GEN-LAST:event_buttonRemoveDomainActionPerformed

private void comboBoxRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRangeActionPerformed
    String name = comboBoxRange.getSelectedItem().toString();
    ((BusinessDelegate)panel.getVistaNuevaOntologia().getModelo()).chageRange(propiedad.getName(),name);
}//GEN-LAST:event_comboBoxRangeActionPerformed

public void addDomain(String name) {
    ((BusinessDelegate)panel.getVistaNuevaOntologia().getModelo()).addDomain(propiedad.getName(),name);
    DefaultListModel mode = (DefaultListModel) listDomain.getModel();
    mode.addElement(name);
}
    
    public void initComponents2(){
        listDomain.setModel(new DefaultListModel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddDomain;
    private javax.swing.JButton buttonChangeName;
    private javax.swing.JButton buttonRemoveDomain;
    private javax.swing.JComboBox comboBoxRange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listDomain;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox getComboBoxRange() {
        return comboBoxRange;
    }

    public void setComboBoxRange(javax.swing.JComboBox comboBoxRange) {
        this.comboBoxRange = comboBoxRange;
    }

    public javax.swing.JList getListDomain() {
        return listDomain;
    }

    public void setListDomain(javax.swing.JList listDomain) {
        this.listDomain = listDomain;
    }

    public javax.swing.JTextField getTextFieldNombre() {
        return textFieldNombre;
    }

    public void setTextFieldNombre(javax.swing.JTextField textFieldNombre) {
        this.textFieldNombre = textFieldNombre;
    }

    public DatatypePropertyVO getPropiedad() {
        return propiedad;
    }

    public void setPropiedad(DatatypePropertyVO propiedad) {
        this.propiedad = propiedad;
    }

}
