/*
 * PanelSinonimos.java
 *
 * Created on 31 de julio de 2008, 23:33
 */

package panels;

import gui.FileChooser;
import controladores.ControladorPanelSinonimos;
import gui.FramePrincipal;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import modelo.BusinessDelegate;
import varios.DefaultListCellEditor;
import varios.DefaultMutableListModel;
import varios.JListMutable;
import vistas.VistaSinonimos;
import vo.IndividualSinonimoVO;

/**
 *
 * @author  Administrador
 */
public class PanelSinonimos extends javax.swing.JPanel {

    private FileChooser chooser;
    private FramePrincipal main;
    private VistaSinonimos vista;
    private String urlOWL;
    private String chooserButton;
    private boolean cargarArbol;
    private TreeSelectionEvent eventoTree;
    private boolean cargarInstancia;
    private boolean agregarSinonimo;
    private boolean agregarTraduccion;
    private boolean removerSinonimo;
    private boolean removerTraduccion;
    
    /** Creates new form PanelSinonimos */
    public PanelSinonimos(FramePrincipal main, VistaSinonimos vista) {
        this.main = main;
        this.vista = vista;
        initComponents();
        initComponents2();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldURL = new javax.swing.JTextField();
        buttonExaminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeIndividual = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonAddSinonimo = new javax.swing.JButton();
        buttonRemoveSinonimo = new javax.swing.JButton();
        buttonAddTraduccion = new javax.swing.JButton();
        buttonRemoveTraduccion = new javax.swing.JButton();
        labelPalabra = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listMutableSinonimos = new JListMutable(new DefaultMutableListModel());
        jScrollPane2 = new javax.swing.JScrollPane();
        listMutableTraduccion = new JListMutable(new DefaultMutableListModel());

        setPreferredSize(new java.awt.Dimension(1023, 532));

        jLabel1.setText("Ontologia Vocabulario");

        buttonExaminar.setText("Examinar");
        buttonExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExaminarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(treeIndividual);

        jLabel2.setText("Palabra");

        jLabel3.setText("Sinonimo");

        jLabel4.setText("Traduccion");

        buttonAddSinonimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add_obj.gif"))); // NOI18N
        buttonAddSinonimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddSinonimoActionPerformed(evt);
            }
        });

        buttonRemoveSinonimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete_obj.gif"))); // NOI18N
        buttonRemoveSinonimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveSinonimoActionPerformed(evt);
            }
        });

        buttonAddTraduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add_obj.gif"))); // NOI18N
        buttonAddTraduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddTraduccionActionPerformed(evt);
            }
        });

        buttonRemoveTraduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete_obj.gif"))); // NOI18N
        buttonRemoveTraduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveTraduccionActionPerformed(evt);
            }
        });

        listMutableSinonimos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(listMutableSinonimos);

        listMutableTraduccion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listMutableTraduccion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(buttonAddTraduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRemoveTraduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                        .addComponent(buttonAddSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRemoveSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(labelPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPalabra, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonRemoveSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddSinonimo)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(buttonAddTraduccion)
                    .addComponent(buttonRemoveTraduccion))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(textFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonExaminar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(474, 474, 474))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buttonExaminar)
                    .addComponent(textFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void buttonExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExaminarActionPerformed
//Filechooser para elegir el archivo owl
    chooser = new FileChooser(main, true, main.getConfiguration().getDefaultURLOWLSinonimos());
    setUrlOWL(chooser.getPath());
    setChooserButton(chooser.getButton());
    if (chooserButton.equals("Cancel")) {

    } else {
            // Cargar los table
            main.getConfiguration().setDefaultURLOWLSinonimos(chooser.getPath());
            ((ControladorPanelSinonimos) vista.getControlador()).doCargarOWL(true);
    }
}//GEN-LAST:event_buttonExaminarActionPerformed


private void buttonCargarActionPerformed(javax.swing.event.TreeSelectionEvent evt) {
        // Cargar solicitud en tablas
        this.eventoTree = evt;
        if(!eventoTree.getPath().getLastPathComponent().toString().equals("Palabras")){
                ((ControladorPanelSinonimos) vista.getControlador()).doCargarInstancia(true);
        }
}


private void buttonAddSinonimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddSinonimoActionPerformed
    ((ControladorPanelSinonimos) vista.getControlador()).doAgregarSinonimo(true);
}//GEN-LAST:event_buttonAddSinonimoActionPerformed

private void buttonAddTraduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddTraduccionActionPerformed
    ((ControladorPanelSinonimos) vista.getControlador()).doAgregarTraduccion(true);    
}//GEN-LAST:event_buttonAddTraduccionActionPerformed

private void buttonRemoveSinonimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveSinonimoActionPerformed
    if(listMutableSinonimos.getSelectedIndex() != -1){
        ((ControladorPanelSinonimos) vista.getControlador()).doRemoverSinonimo(true);
    }
}//GEN-LAST:event_buttonRemoveSinonimoActionPerformed

private void buttonRemoveTraduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveTraduccionActionPerformed
    if(listMutableTraduccion.getSelectedIndex() != -1){
        ((ControladorPanelSinonimos) vista.getControlador()).doRemoverTraduccion(true);
    }
}//GEN-LAST:event_buttonRemoveTraduccionActionPerformed

public void update() {
    if(cargarArbol){
        cargarTree();
        if(cargarInstancia){
            cargarIndividualInPanel();
        }else{
            if(isAgregarSinonimo()){
                agregarSinonimo();
                grabarOntologiaVocabulario();
            } else if(isAgregarTraduccion()){
                agregarTraduccion();
                grabarOntologiaVocabulario();
            } else if(isRemoverSinonimo()){
                removerSinonimo();
                grabarOntologiaVocabulario();
            } else if(isRemoverTraduccion()){
                removerTraduccion();
                grabarOntologiaVocabulario();
            } else{
                
            }
        }
    }else{
        
    }
}

public void agregarSinonimo(){
    
}

public void agregarTraduccion(){
    
}

public void removerSinonimo(){
    
}

public void removerTraduccion(){
    
}

public void grabarOntologiaVocabulario(){
    
}

public void cargarIndividualInPanel(){
    String instancia = eventoTree.getPath().getLastPathComponent().toString();
    IndividualSinonimoVO individual = (IndividualSinonimoVO) ((BusinessDelegate)vista.getModelo()).obtenerIndividual(instancia);
    ArrayList<String> sinonimos = individual.getSinonimos();
    ArrayList<String> traduccion = individual.getTraduccion();
    String nombre = individual.getNombreInstancia();
    labelPalabra.setText(nombre);
    listMutableSinonimos.setModel(new DefaultMutableListModel());
    DefaultMutableListModel dlm = (DefaultMutableListModel) listMutableSinonimos.getModel();
    
    Iterator itSin = sinonimos.iterator();
    while(itSin.hasNext()){
        dlm.addElement(itSin.next().toString());
    }
    
    listMutableTraduccion.setModel(new DefaultMutableListModel());
    DefaultMutableListModel dlm2 = (DefaultMutableListModel) listMutableTraduccion.getModel();
    Iterator itTra = traduccion.iterator();
    while(itTra.hasNext()){
        dlm2.addElement(itTra.next().toString());
    }
}

public void cargarTree(){
    ArrayList<String> individuals = (ArrayList<String>) ((BusinessDelegate)vista.getModelo()).obtenerInstanciasVocabuario(urlOWL);

    DefaultMutableTreeNode abuelo = new DefaultMutableTreeNode("Palabras");
    DefaultTreeModel modelo = new DefaultTreeModel(abuelo);
    treeIndividual = new JTree(modelo);
    DefaultMutableTreeNode[] padre = new DefaultMutableTreeNode[individuals.size()];
    Iterator it = individuals.iterator();
    int i = 0;
    while(it.hasNext()){
            padre[i] = new DefaultMutableTreeNode(it.next().toString());
            i++;
    }
    for(int j = 0 ; j < padre.length ; j++){
            modelo.insertNodeInto(padre[j],abuelo, j);
    }
    treeIndividual.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
    public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
            buttonCargarActionPerformed(evt);    
    }
    });
    jScrollPane1.setViewportView(treeIndividual);
    Object root = treeIndividual.getModel().getRoot();
    TreePath path = new TreePath(root);
    treeIndividual.expandPath(path);
}


public void setCargarArbol(boolean flag){
    this.cargarArbol = flag;
}


private void initComponents2(){
    DefaultMutableTreeNode abuelo = new DefaultMutableTreeNode("Palabras");
    DefaultTreeModel modelo = new DefaultTreeModel(abuelo);
    treeIndividual = new JTree(modelo);
    jScrollPane1.setViewportView(treeIndividual);
    
    //Crear lista mutable sinonimos
    
    JTextField tf = new JTextField();
    tf.setBorder(BorderFactory.createLineBorder(Color.black));
    listMutableSinonimos.setListCellEditor(new DefaultListCellEditor(tf));
    listMutableSinonimos.setVisibleRowCount(-1);
    
    //Crear lista mutable traduccion
    
    JTextField tf2 = new JTextField();
    tf.setBorder(BorderFactory.createLineBorder(Color.black));
    listMutableTraduccion.setListCellEditor(new DefaultListCellEditor(tf2));
    listMutableTraduccion.setVisibleRowCount(-1);
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddSinonimo;
    private javax.swing.JButton buttonAddTraduccion;
    private javax.swing.JButton buttonExaminar;
    private javax.swing.JButton buttonRemoveSinonimo;
    private javax.swing.JButton buttonRemoveTraduccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelPalabra;
    private varios.JListMutable listMutableSinonimos;
    private varios.JListMutable listMutableTraduccion;
    private javax.swing.JTextField textFieldURL;
    private javax.swing.JTree treeIndividual;
    // End of variables declaration//GEN-END:variables

    public String getUrlOWL() {
        return urlOWL;
    }

    public void setUrlOWL(String urlOWL) {
        this.urlOWL = urlOWL;
    }

    public String getChooserButton() {
        return chooserButton;
    }

    public void setChooserButton(String chooserButton) {
        this.chooserButton = chooserButton;
    }

    public boolean isCargarInstancia() {
        return cargarInstancia;
    }

    public void setCargarInstancia(boolean cargarInstancia) {
        this.cargarInstancia = cargarInstancia;
    }

    public boolean isAgregarSinonimo() {
        return agregarSinonimo;
    }

    public void setAgregarSinonimo(boolean agregarSinonimo) {
        this.agregarSinonimo = agregarSinonimo;
    }

    public boolean isAgregarTraduccion() {
        return agregarTraduccion;
    }

    public void setAgregarTraduccion(boolean agregarTraduccion) {
        this.agregarTraduccion = agregarTraduccion;
    }

    public boolean isRemoverSinonimo() {
        return removerSinonimo;
    }

    public void setRemoverSinonimo(boolean removerSinonimo) {
        this.removerSinonimo = removerSinonimo;
    }

    public boolean isRemoverTraduccion() {
        return removerTraduccion;
    }

    public void setRemoverTraduccion(boolean removerTraduccion) {
        this.removerTraduccion = removerTraduccion;
    }

}
